"""add recovery attempts column

Revision ID: 9a766e81ecac
Revises: a8529f40cb49
Create Date: 2026-03-31 15:12:24.556772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a766e81ecac'
down_revision = 'a8529f40cb49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recovery_attempts', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('recovery_attempts')

    # ### end Alembic commands ###
