"""create inventory table

Revision ID: a8529f40cb49
Revises: b378d729ded3
Create Date: 2026-03-31 12:22:40.833224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8529f40cb49'
down_revision = 'b378d729ded3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('item_name')
    )
    # ### end Alembic commands ###

    # Manually added — seed initial stock.
    # Burger = 5 intentionally for the Phase 5 concurrency test:
    # "Only 5 burgers available, 10 concurrent orders arrive"
    op.bulk_insert(
        sa.table(
            'inventory',
            sa.column('item_name', sa.String),
            sa.column('quantity', sa.Integer),
        ),
        [
            {"item_name": "Burger",     "quantity": 5},
            {"item_name": "Fries",      "quantity": 50},
            {"item_name": "Pizza",      "quantity": 20},
            {"item_name": "Croissants", "quantity": 30},
            {"item_name": "Coffee",     "quantity": 100},
            {"item_name": "Sandwich",   "quantity": 25},
            {"item_name": "Salad",      "quantity": 15},
            {"item_name": "Pasta",      "quantity": 20},
        ]
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory')
    # ### end Alembic commands ###